-- 1. Сначала убедимся, что схема для чистых данных существует
CREATE SCHEMA IF NOT EXISTS AIRLINES_DWH.CORE_DATA;

-- 2. Создаем таблицу AIRLINES в схеме CORE_DATA
-- Мы наполняем её данными, которые выбираем из RAW_DATA
CREATE OR REPLACE TABLE AIRLINES_DWH.CORE_DATA.AIRLINES AS
SELECT 
    -- Убираем пробелы
    TRIM(PASSENGER_ID) AS PASSENGER_ID,
    TRIM(FIRST_NAME) AS FIRST_NAME,
    TRIM(LAST_NAME) AS LAST_NAME,
    TRIM(GENDER) AS GENDER,
    
    -- Пытаемся превратить возраст в число (Чистка)
    TRY_TO_NUMBER(AGE) AS AGE,
    
    TRIM(NATIONALITY) AS NATIONALITY,
    TRIM(AIRPORT_NAME) AS AIRPORT_NAME,
    TRIM(AIRPORT_COUNTRY_CODE) AS AIRPORT_COUNTRY_CODE,
    TRIM(COUNTRY_NAME) AS COUNTRY_NAME,
    TRIM(AIRPORT_CONTINENT) AS AIRPORT_CONTINENT,
    TRIM(CONTINENTS) AS CONTINENTS,
    
    -- Пытаемся превратить дату в нормальный формат YYYY-MM-DD
    TRY_TO_DATE(DEPARTURE_DATE, 'MM/DD/YYYY') AS DEPARTURE_DATE,
    
    TRIM(ARRIVAL_AIRPORT) AS ARRIVAL_AIRPORT,
    TRIM(PILOT_NAME) AS PILOT_NAME,
    TRIM(FLIGHT_STATUS) AS FLIGHT_STATUS,
    TRIM(TICKET_TYPE) AS TICKET_TYPE,
    TRIM(PASSENGER_STATUS) AS PASSENGER_STATUS
    
FROM AIRLINES_DWH.RAW_DATA.AIRLINES_RAW;