USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE COMPUTE_WH 
WITH WAREHOUSE_SIZE = 'X-SMALL' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE AIRLINES_DWH;

CREATE OR REPLACE SCHEMA AIRLINES_DWH.RAW_DATA;

CREATE OR REPLACE SCHEMA AIRLINES_DWH.ANALYTICS;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE AIRLINES_DWH;
USE SCHEMA RAW_DATA;