USE ROLE ACCOUNTADMIN;
USE DATABASE AIRLINES_DWH;

CREATE SCHEMA IF NOT EXISTS CORE_DATA;
CREATE SCHEMA IF NOT EXISTS METADATA;

CREATE OR REPLACE TABLE CORE_DATA.AIRLINES (
    PASSENGER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    AGE NUMBER,
    DEPARTURE_DATE DATE,
    FLIGHT_STATUS VARCHAR,
    AIRPORT_COUNTRY_CODE VARCHAR,
    COUNTRY_NAME VARCHAR,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE METADATA.AUDIT_LOG (
    LOG_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PROCESS_NAME VARCHAR(100),
    STATUS VARCHAR(50),
    ROWS_AFFECTED INT,
    LOG_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ERROR_MESSAGE VARCHAR
);

CREATE OR REPLACE STREAM RAW_DATA.AIRLINES_STREAM 
ON TABLE RAW_DATA.AIRLINES_RAW;




