USE ROLE ACCOUNTADMIN;
USE DATABASE AIRLINES_DWH;

CREATE ROLE IF NOT EXISTS JUNIOR_ANALYST;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE JUNIOR_ANALYST;
GRANT USAGE ON DATABASE AIRLINES_DWH TO ROLE JUNIOR_ANALYST;
GRANT USAGE ON SCHEMA AIRLINES_DWH.CORE_DATA TO ROLE JUNIOR_ANALYST;

GRANT SELECT ON TABLE AIRLINES_DWH.CORE_DATA.AIRLINES TO ROLE JUNIOR_ANALYST;

CREATE OR REPLACE ROW ACCESS POLICY US_ONLY_POLICY 
AS (country_code VARCHAR) RETURNS BOOLEAN ->
  CASE 
      WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN TRUE 
      WHEN CURRENT_ROLE() = 'JUNIOR_ANALYST' AND country_code = 'US' THEN TRUE
      ELSE FALSE
  END;


ALTER TABLE AIRLINES_DWH.CORE_DATA.AIRLINES 
ADD ROW ACCESS POLICY US_ONLY_POLICY ON (AIRPORT_COUNTRY_CODE);


CREATE OR REPLACE SECURE VIEW AIRLINES_DWH.CORE_DATA.SECURE_AIRLINES_REPORT AS 
SELECT 
    PASSENGER_ID, 
    FIRST_NAME, 
    FLIGHT_STATUS, 
    AIRPORT_COUNTRY_CODE 
FROM AIRLINES_DWH.CORE_DATA.AIRLINES;

GRANT SELECT ON VIEW AIRLINES_DWH.CORE_DATA.SECURE_AIRLINES_REPORT TO ROLE JUNIOR_ANALYST;

SELECT DISTINCT AIRPORT_COUNTRY_CODE FROM AIRLINES_DWH.CORE_DATA.AIRLINES;


GRANT ROLE JUNIOR_ANALYST TO USER LILISTRIGALEVA;

USE ROLE JUNIOR_ANALYST;
SELECT DISTINCT AIRPORT_COUNTRY_CODE FROM AIRLINES_DWH.CORE_DATA.AIRLINES;